haskell-indent.el
Mark haskell-indent-offset, haskell-indent-literate-Bird-default-offset,
haskell-indent-rhs-align-column, haskell-indent-look-past-empty-line and
haskell-indent-thenelse as safe file local variables.
=> Mark some variables as safe.

tests/haskell-simple-indent-tests.el
For now testing only haskell-simple-indent function.
=> Add haskell-simple-indent-tests.el.

haskell-commands.el
Added all hasktags supported formats: *.hs, *.lhs and *.hsc.
It used to take also emacs backup files like "*.hs~". This is no longer
the case.
Fixes  #199.
=> Generate tags from *.hs, *.lhs and *.hsc only.

Makefile, haskell-mode.texi
=> Pr haskell info fixes

haskell-mode.el
Change paragraph-start and paragraph-separate so that haddock (-- |)
and nested comments become paragraphs; only empty lines used to be
paragraph separators. This also makes forward/backward-paragraph more
helpful.
Change haskell-fill-paragraph to recognize nested comments slightly
more accurately using forward-sexp. Also, if fill-paragraph was called
in a nested and no actual filling is necessary, make sure
non-comment-aware filling does not happen instead.
=> Improve paragraph filling for nested comments.

haskell-interactive-mode.el
New functions:
- `haskell-interactive-mode-next-prompt`
- `haskell-interactive-mode-prev-prompt`
New keybindings in `haskell-interactive-mode-map`:
- `C-c C-n` jump to next prompt
- `C-c C-p` jump to previous prompt
[![24pullrequests](http://24pullrequests.com/assets/logo-625222452ffc0d57272decb6f851a7fe.png)](http://24pullrequests.com)
Best,
Markus
=> Jump to next/previous prompt in haskell-interactive-mode

haskell-font-lock.el
This commit correctly highlights 'as' and 'hiding' as keywords in
statement:
import "package" A.B.C as C hiding (f)
Fixes #184.
=> Add PackageImports syntax to font-lock.

haskell-font-lock.el
Make definition like
func !b
highlight like bang pattern not like a definition of (!) operator.
Fixes #147.
=> Special case bang pattern for font-lock.

haskell-simple-indent.el
Improve documentation for haskell-simple-indent with example of
multiline position calculation.
=> Improve docs for haskell-simple-indent.

haskell-simple-indent.el
haskell-comment-function is useful when auto-fill-mode is enabled and comments are expected to auto-fill. This function keeps comments nicely aligned.
Fixes #279.
Note that multiline-style comments are still not supported for auto-fill mode.
=> Implement haskell-comment-function.

tests/haskell-indent-tests.el
Add haskell-indent-tests.el, first two tests check haskell-indent-put-region-in-literate.
Fixes #88 in the sense that it proves there is no bug on Emacsen that we tests with.
=> Add haskell-indent-tests.el.

haskell-mode.el, tests/haskell-mode-tests.el
Fixes and tests for comment paragraph fill.
Ref #393.
=> M-q fix and tests

haskell-simple-indent.el, tests/haskell-simple-indent-tests.el
Keep point in sane positions after haskell-simple-indent. This commit
solves multiple problems:
- messing line content when indent offset was not found
- getting to the biggining of line in couple of cases
- failing to indent second line in the buffer in some cases
Make indentation more predictable to users.
=> Keep point in haskell-simple-indent.

haskell.el
I noticed that haskell-mode wasn't doing this, because ghci needs to be passed the "import " string to make it complete the module name after.
I also changed the behaviour so that it would not forcefully start a new process if there isn't one already running. I think this is standard behaviour in other modes, and it can be intrusive because it is the first thing that happens when I open a new file and it asks several questions about the new session before I can do anything else.
=> Allow module name completion in import statements

tests/haskell-simple-indent-tests.el
indent-tabs-mode is buffer local when set anyway.
=> Use setq in place of setq-local for indent-tabs-mode.

haskell-font-lock.el
Font lock for `M.v` should be operator face same as `v`.
Fixes #438.
=> Operator `M.v` font lock.

haskell-font-lock.el
Some rather obvious improvements to haskell-font-lock.
=> Pr font lock 1

haskell-cabal.el
A generalised version of what I proposed in #464.
=> Guess a project's setting from it's .cabal file

haskell-commands.el
The `find' invocation was only generating any output for *.hsc files.
=> Make haskell-process-generate-tags really output TAGS

tests/haskell-indent-tests.el
Document assertion failure reported in #415.
module Test where
-- {{{ A header
--
! <-- TAB here
Results in
(or (<= start end) (signal (quote cl-assertion-failed)...
=> Document assertion in haskell-indent.

haskell-cabal.el
This prevents the insertion of unwanted tabs in the cabal file when
auto-inserting dependencies, regardless of the user value for
`indent-tabs-mode` in the default mode (default is fundamental mode).
Solves issues #379 and #474.
=> Force temp buffer to use spaces for indentation.

haskell-session.el, haskell-str.el, haskell-string.el
Emacs has string-prefix-p and string-suffix-p. Use them when needed.
=> Pr fix string suffix prefix

haskell-mode.el
Emacs defines 'w' class as word chars and '_' as set that together with
'w' can form identifiers. Note that by this operators in programming
languages fall under punctuation '.' class and are treated as such by
for example c-mode, java-mode, etc.
It is confusing that characters defined in Haskell Report as 'symbol'
are NOT the same as 'symbol' character class defined in Emacs.
Fixes #311.
=> Put Haskell symbol chars in punctuation char class.

haskell-font-lock.el
Do to some idiocy on my part, I am reopening a pull request to fix the Haddock comment regexp.  Please see the now-closed pull request #453 for some discussion and an example.
It should now only allow the following to be recognized as starting Haddock comments:
-- docsym
{-docsym
{- docsym
=> Fix Haddock comment regexp

haskell-cabal.el
When on an empty line in a .cabal file, tab does an indent-relative (which was the previous behaviour).  Currently, it does nothing, so you have to hit space etc.
=> haskell-cabal indent-relative on empty

haskell-font-lock.el
=> Properly delimit reserverd symbols.

ghc-core.el, ghci-script-mode.el
Some auto-mode-alist settings didn't have an autoload cookie applied
(correctly), making them effectively useless.  Add the missing cookies
to make the behavior consistent.
=> Add missing autoload cookies

haskell-font-lock.el
The regular expression was incorrectly matching `=======` without a
space afterwards, so headings were being incorrectly colored as
warnings.
=> Fix font-lock-warning-face regular expression

haskell-font-lock.el
`>>>>>>>` and `<<<<<<<` have text after, but `|||||||` and `=======`
do not.
=> Correct marker regexes

haskell-customize.el, haskell-load.el, haskell-modules.el, haskell-package.el, haskell-process.el, tests/haskell-process-tests.el
=> Remove all mentions of cabal-dev.

haskell-commands.el, haskell-customize.el, haskell-doc.el, haskell-interactive-mode.el
See #432 for what this is supposed to do. I'm not sure if I missed some corner cases, or if I broke something that I don't use myself. Is `haskell-process` the right function to check if there's a running process available?
I don't want to make synchronous calls to ghci, so the way it's written now it only works for eldoc because other functions that get type information seem to be synchronous.
Why is all this in haskell-doc anyway? Isn't a lot of it duplicating eldoc-mode?
Some of the commented-out code in haskell-doc.el and todo-items are from 2001, btw :)
=> Haskell eldoc support with ghci in haskell-interaction-mode.

haskell-font-lock.el
Improve haddock font lock propagation as this was a potentially expensive piece of code. Now it does a more local processing (previous line at most).
=> Cleanup haddock font lock

haskell-process.el, tests/haskell-process-tests.el
The session target needs to be wrapped too otherwise it gets passed as an argument to the wrapping command.
=> Wrap session target

haskell-mode.el
Wasn't exactly sure what was idiomatic for defcustom variables in haskell-mode.  I find the fp-complete site better.
=> Added haskell-hoogle-url

haskell-mode.el
It looked like the hard-coded url was being redirected to a new url, and went with the new one as the default.  Added url-hexify-string to query.
=> Added haskell-hayoo-url as a custom variable

haskell-cabal.el
As requested by @gracjan in #506, this makes `haskell-cabal-find-file` check that the provided directory actually exists before using it to search for a .cabal file.
=> Ensure directory exists before searching for a .cabal file

haskell-cabal.el
It defaults to the directory of the current buffer already.
=> No need to specify a directory when calling cabal-find-file

haskell-font-lock.el
Fontify pragmas while fontifying comments. 	
Change default of haskell-pragma-face to font-lock-preprocessor-face as
this is closer to semantic meaning of a similar #pragma construct in cpp.
=> Cleanup pragma font lock {-# .. #-}

haskell-font-lock.el
Double dash start a comment only when it is not a part of larger lexeme
that has symbols other than dashes. Take care of this situation properly.
=> Detect advanced -- comments.

haskell-font-lock.el, haskell-mode.el
Fixes #497, #181.
Related #324.
=> Pr implement gap rule

haskell-font-lock.el, haskell-mode.el
=> Direct users to smerge-mode for conflict markers.

haskell-repl.el
=> Fix evil-mode results,

haskell-font-lock.el
=> Stop overreacting when seeing three backslashes.

haskell-commands.el
=> Dim stylish-haskell errors.

haskell-mode.el
Move documentation of haskell-mode-hook into haskell-mode proper.
define-derived-mode defines haskell-mode-hook that gets in conflict with
defcustom haskell-mode-hook. Some Emacsen (notably Aquamacs) have issues
with double defined variables and are not able to show the documentation
properly nor use customize functionality.
=> Clean up haskell-mode-hook.

README.md
Write up to date information for newcomers.
=> Update instructions in README.md.

haskell-commands.el
=> Fix haskell-docs invocation.

haskell-commands.el
`(goto-char)` does not switch buffer; thus the buffer of `initial-loc` did not get pushed into `xref--marker-ring`/`find-tag-marker-ring`.
=> Fix buffer in the marker pushed by xref-push-marker-stack

haskell-font-lock.el
This set of commits modernizes what font locking definition is doing.
=> Improve multiple issues with font lock

haskell-font-lock.el
=> Properly delimit operators in prettify mode.

haskell-font-lock.el
Use faces directy as symbols not as variables. As per font-lock
documentation:
Note that in new code, in the vast majority of cases there is no need to
create variables that specify face names.  Simply using faces directly
is enough.  Font-lock is not a template to be followed in this area.
=> Use faces directly.

haskell-mode.texi
There is small typo in haskell-cabal-mode manual section, ``eval-after-load`` FORM must be quoted.
=> Typo in haskell-cabal-mode manual.

haskell-commands.el
Tested:
+ (haskell-process-generate-tags) ⇒ "Tags generated."
+ (haskell-process-generate-tags "SomeTag") ⇒ jumps to tag definition
_Sorry, I can't get rid of first commit (without delete and re-fork)._
=> Use tags-table-list instead of tags-file-name

haskell-customize.el, haskell-yas.el, haskell.el, snippets/haskell-mode/lang-pragma
Similar to a previous PR, this adds completion for LANGUAGE and OPTIONS ghc pragmas inside comments, using ghci's `:complete repl ":set ..."`, which understands all language/option flags.
It's not spectacularly useful because normally (?) you'd need to type the first three (?) characters yourself before completion kicks in.
I also made a small change to some previous code to avoid some unnecessary string -> symbol -> string conversion.
=> OPTIONS and LANGUAGE completion using ghci

haskell-font-lock.el
As per https://github.com/haskell/haskell-mode/issues/589
Seems to work pretty well but I'm welcome to alternatives!
I removed the ```forall``` check since it seems redundant now.
=> Dot composition detection

haskell.el
Currently **Emacs-snapshot** Travis-CI build fails with following error:
> In toplevel form:
> haskell.el:90:63:Error: looking-back called with 1 argument, but requires 2-3
> make: *** [haskell.elc] Error 1
~~According to documentaion of `looking-back` function in recent version
of Emacs, second and third arguments are optional. Second argument is
LIMIT, here is what documented:~~
> ~~LIMIT if non-nil speeds up the search by specifying a minimum~~
> ~~starting position, to avoid checking matches that would start~~
> ~~before LIMIT.~~
~~Thus, it turns that we can safely provide `nil` as LIMIT, which will not
affect current bahavoiur, but will fix error message.~~
Updated as suggested by @gracjan.
=> Fix Emacs-snapshot build

haskell-commands.el, haskell-doc.el, haskell-mode.el, haskell.el, inf-haskell.el, tests/haskell-mode-tests.el
The documentation mandates that `haskell-ident-at-point` and `haskell-ident-pos-at-point` return `nil` if there is no identifier at point.  However:
1. Apparently, at some point `haskell-ident-at-point` instead returned `""` in that case.
2. Currently, `haskell-ident-pos-at-point` instead returns a cons cell of the form `(n . n)` in that case.
This pull request fixes two things:
1. Some code assumed that `haskell-ident-at-point` always returned a string; these assumptions have all been fixed.  (Commit f8521d90e7c200c07a84328c8d19e2993aad15ac.)
2. `haskell-ident-pos-at-point` now returns `nil` correctly, and any code relying on the old behavior was fixed.  (Commit 6a3257c54cf77084d106483090c393e18331cc4d.)
(Fixing `haskell-ident-pos-at-point` indirectly fixes …
=> Fix `haskell-ident-at-point` uses and `haskell-ident-pos-at-point` behavior

haskell-commands.el, haskell-interactive-mode.el, haskell-presentation-mode.el, haskell-session.el
Simplify `haskell-present`:
+ do not apply text properties to hint and fontification to buffer,
because  presentaions are fontified according to haskell mode
automatically
+ properly assing presentation buffer to haskell session
+ make buffer readonly
Rename `haskell-process-do-simple-echo` to
`haskell-process-show-repl-response` and remove redundant mode argument
Update doc strings
=> Tidy up `haskell-present` and `haskell-process-do-simple-echo` according to #607

haskell-font-lock.el
This was wrongly used and only for the case of qvarid.
=> Remove haskell-default-face.

Makefile, README.md, haskell-mode.texi
`make all` proceeds as normal, save for not generating a tar.
=> Removes references to Marmalade in documentation and build process. Closes #626.

haskell-doc.el, haskell.el
Because ?. has punctuation syntax, it doesn't get recognized as a symbol
constituent.
See also #639
=> Use haskell-ident-at-point, not thing-at-point

haskell-commands.el
Make `haskell-mode-show-type-at` function aware of presentation mode.
Refactored code a bit: bind multiple occurances of
`(haskell-fontify-as-mode ty 'haskell-mode)` to variable `fty`.
=> Support presentaion mode by `haskell-mode-show-type-at`

haskell-commands.el
Is there a way to place hyperlink to function documentation in echo area?
=> Better error handling for `haskell-mode-show-type-at`

haskell-commands.el, haskell-utils.el
Move var declaration to the top
Restructure code a bit
Remove extra whitespace from haskell-utils.el
=> Rename prefix `hs-utils/` to `haskell-utils-`

haskell-process.el
Make buffer read only after append
This solution makes haskell process log buffer to autoscroll if point was at the end of buffer before appending, otherwise this will append message and preserve original point position. This also behaves correctly if several windows contain log buffer, for example having one window with point at the end and another window with point somewhere else, it will scroll first buffer, and preserve point position in second.
Thanks to **YongFrog**'s answer http://emacs.stackexchange.com/a/12346/6844.
=> Effective append to haskell process log buffer.

haskell-commands.el, haskell-compat.el, haskell.el
Emacs 25 deprecates `find-tag'.  See issue #655.
=> use `xref-find-definitons' instead of `find-tag'

haskell-indentation.el
Related to https://github.com/haskell/haskell-mode/issues/658
I want to touch documentation a bit before merge.
=> Disable show identations by default

Makefile
This should be replaced with Emacs based validation. Flycheck does it,
we should check how it does it and use same method in Makefile.
=> Remove menu order checking

haskell-font-lock.el
Highlighting issues with strings containing
double-quotes with backslashes
@gracjan I tried to squash the commits, and it caused some problems with the PR. So sending a new one.
=> Fix three backslash in string issue, fixes #683

doc/haskell-mode.texi, haskell-indentation.el
=> Obsolete turn-on/off-hi

haskell-font-lock.el
Make it continue even if content has '|' in it.
=> Improve QuasiQuote font lock

haskell-font-lock.el
This reverts commit 3b7c635c0e3180cd7b157a0d1a1df0c12ca07691.
ghc-mod depends on this functionality.
=> Revert "Remove turn-on/off-haskell-font-lock."

haskell-commands.el, haskell-interactive-mode.el, haskell-presentation-mode.el
Fixes:
+ buffer creation
+ mode mappings
=> Haskell presentaions fix

haskell-commands.el
=> Minor improvements of `haskell-process-show-type-at` command 

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Handle instance context in haskell-indentation

haskell-indentation.el
The GHC lexer actually uses the symbols ⤙ and ⤚ for arrow notation, and
these are the glyphs which the listed code-points and Unicode names in
the file refer to. However, the table from the GHC documentation, from
which the symbols in haskell-indentation.el seem to have been copied,
currently lists the wrong glyphs for these codepoints.
Cf.  [lexer source](https://github.com/ghc/ghc/blob/master/compiler/parser/Lexer.x). I’ve already filed a bug against the GHC docs.
=> Fix indentation unicode symbols.

tests/haskell-indentation-tests.el
This automatically transforms check input to UnicodeSyntax and
runs the test twice; once on the original, once on the Unicode
version.
Note that I don’t really know what I’m doing with my Elisp. Is this
usable to you? In my test it catches #715.
Since this is using a dumb search&replace, instead of requiring
separate tests for Unicode cases, e. g. things like `->` can’t be used
in Haskell strings inside of the test cases, which is probably not an
issue.
=> Test suite: Do checks on UnicodeSyntax, too.

Makefile, haskell-completions.el, tests/haskell-completions-tests.el
Let's move a little by little.  This is starting point for completion package.
I'm unsatisfied with tests because when some assertions are failed it's quite hard to find which one is actual culprit.  I'd rather split all tests into separate functions, but this will bring a lot of boilerplate code.  I've looked at `defmacro` and `haskell-indentation-check` function but have found no good replacement yet and gave up.  So, let's merge this as is, and improve tests later.
Related #688
=> Completions package

haskell-completions.el, haskell.el, tests/haskell-completions-tests.el
This is long story. I want to make some improvements on completion stuff.
I will add changes step by step because a bit short in time and made this PR to have some feedback and help.
=> Completion mechanics haskell-completions-grab-prefix implementation

haskell-completions.el
New function also provides a completions inside comments and string literals using `dabbrev` expansions, provide completions for pragmas (need some minor improvements for `CONLIKE` and `SPECIALIZE` pragmas), GHC options completions, language extensions, module names and arbitrary identifiers.
=> New synchronous completion function

haskell.el
New method have following features:
+ provide completions inside comments and string literals using `dabbrev` expansion
+ provide completions for pragmas (e.g. LANGUAGE, DEPRECATED, etc.)
+ provide completions for supported GHC options
+ provide completions for language extensions
+ provide completions for module names using
+ provide completions for arbitrary haskell identifiers
+ prevent Emacs to hang in case if REPL is busy
Old method does not provided completions for pragma names and words inside comments and strings.  Also it fetches completions by synchronous REPL query, this will hang Emacs for a while if REPL is busy.  New method fallbacks to dabbrev expansions immediately in this case, though the result is worst.  Old method does not provide completions for local names (e.g. …
=> Replace old completion function with new one

haskell-customize.el, haskell-mode.el
Turn `haskell-ghc-supported-extensions` and
`haskell-ghc-supported-options` into variables, move them outside
customize package to haskell-mode one.
Related to #730
=> Turn few customizable options to variables

haskell.el
This commit removes counter-intuitive logic when bringing a project buffer to the front.
One could argue that we want to make the old behavior configurable. If so, please comment here and I'll add a config option.
Fixes #710.
=> `haskell-interactive-bring': Use `pop-to-buffer'.

haskell-customize.el, haskell-process.el
Add stack ghci support from #744. Also fix a defcustom typo in haskell-process-args-cabal-repl.
=> Add support for interaction with stack ghci.

haskell-load.el
At least for newer ghc versions the line here looks like
```
It is a member of the hidden package ‘xml-conduit-1.3.0@xmlco_BftDMkVAlkEFsqbeX22lfX’.
```
so only the part before the `@` should be considered.
=> Fix regex for package version detection

Makefile
Otherwise, compilation order is important and since we don't respect it,
compilation may break when outdated elc files are around. The workaround
implemented here only works in Emacs 24.4 or later.
Close #755
=> build: when compiling, don't rely on old elc files

haskell-customize.el, haskell-process.el
=> Remove cabal-ghci #486

Makefile, haskell-lexeme.el, tests/haskell-lexeme-tests.el
Implement Haskell tokenizer, with all bells a whistles, Unicode support, all GHC special cases and stuff.
Related to #724.
=> Add haskell-lexeme.el

haskell-mode.el
Based on tokenizer work implement `forward-sexp` that works with Haskell.
(Note that this only works forward, backward falls back to Emacs native function.)
Fixes #648.
=> Implement haskell-forward-sexp

haskell-customize.el, haskell-session.el, haskell-utils.el, haskell.el
- Added `haskell-process-load-or-reload-p` variable with default value `t` meaning "do make prompt", so current flow is not changed unless user changes the variable to `nil`.
-  Three functions changed just to check for `haskell-process-load-or-reload-p` variable and, depending on its value, make a prompt or accept the default:
`haskell-session-new-assume-from-cabal`
`haskell-utils-read-directory-name`
`haskell-session-target`
=> New variable to allow user to enable/disable prompts on starting REPL

haskell-decl-scan.el, haskell-doc.el, haskell-simple-indent.el
This is still a work in progress, I just want some feedback on what I have done, and what I still need to do.
1. Does it make sense to convert `turn-on-haskell-font-lock` into a minor mode?
2. I'm not really sure what to do with `turn-on-haskell-unicode-input-method`. It honestly seems fine as it is.
3. I plan on converting `turn-on-haskell-indent` into a minor mode similar to `haskell-indentation-mode`.
Fix #771
=> Mark various turn-on-haskell-* functions obsolete

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Implemente layout rule more properly

haskell-process.el
+ Add options argument to `haskell-process-get-repl-completions` setting
completion candidates limit
+ Remove unused item from resulting candidates list.  This item is not
completion itself but unused part of input string (see issue #776 for
more details).
=> Add optional candidates limit arg, remove unused item from result

haskell-load.el
When using `stack-ghci` as a `haskell-process-type`, attempting to invoke `haskell-process-do-cabal` (or any such derived command, such as `haskell-process-cabal-build`) fails due to insufficiently comprehensive `cl-ecase` statements in haskell-load.el. Handling `stack-ghci` in these case statements makes `haskell-process-do-cabal` work as expected.
=> Correctly match 'stack-ghci when running haskell-process-do-cabal.

haskell-cabal.el
This commit fixes #784. When `haskell-process-load-or-reload-prompt` is
set to `nil`, `haskell-cabal-get-dir` used to return `nil` when there is
no Cabal project. Now it returns `default-directory` instead.
=> Determine proper default Cabal directory when no Cabal project

haskell-load.el
=> Fix #803:  save-excursion in haskell-process-errors-warnings

haskell-cabal.el, haskell-commands.el, haskell-session.el, haskell-utils.el
..by untangling the madness around `haskell-session-pwd`.
The names didn't correspond to the actual meanings, the branches and arguments were unused..
=> Restore `haskell-process-cd` functionality..

haskell-process.el
It seems that the issue #787 might be due to the "unused string" (h1) being not in completions list (cs). This commit reverts part of the commit f0466a2 back to the earlier version, where the unused string (h1) is placed at beginning of the completions list (cs).
=> Add unused string in completions as well.

haskell-indentation.el, haskell-mode.el
Various cosmetic corrections. All the changes do not introduce any
differences in functioning of the module, this is just refactoring.
Added TODO items:
* TODO eliminate magic number 2 where possible, use a variable
* TODO `haskell-indentation-find-indentation' — fix it, get rid of "safe"
version
I've written doc-strings where possible. Many functions still need
decent doc-strings, I've marked them with FIXME. It's possible that I'll
add doc-string of these functions later. N.B. the module is quite hairy,
so you should have really good doc-strings here.
=> Cosmetic changes in ‘haskel-indentation.el’

tests/haskell-indentation-tests.el
Here is better helper for testing, a macro to eliminate boilerplate and more dense tests. Three last tests are strange (commented). Also, I don't know if contents of current line should affect found indentations or collection of indentation columns is completely defined by context set in previous lines.
Criticism is welcome. I haven't silenced failing tests for now.
Note that it's always clear which "sub-case" failed because I compare positions too, so they are shown when something fails, this also helps ensuring that point can be placed in specified position.
=> Better tests for ‘haskell-indentation-mode’

haskell.el
`'` should be used rather than `#'` in `make-obsolete` and `#'` causes byte-compile warning.  You can get following warning by following steps.
1. byte-compile `haskell.el`
2. load `haskell.elc`
3. byte-compile `haskell.el`
```
haskell.el:67:2:Warning: `haskell-process-completions-at-point' is an obsolete
function (as of June 19, 2015); use
`haskell-completions-sync-completions-at-point' instead.
```
=> Suppress byte-compile warning

doc/haskell-mode.texi
Small description of the `haskell-session-change-target` function and its usage for testing and benchmarking.
=> Describe haskell-session-change-target for test & bencmark, #817

haskell-indentation.el
The warning report system of the byte-compiler is not perfect.
It generates the warning if the third argument of `dotimes` is used.
Also, it does so if the first argument is not explicitly used in its body.
As workaround, this patch removes the third argument and put "_" to
the first argument.
Relating to #815 and #827.
=> Prevent the unused variable warning

haskell-decl-scan.el
symbol-value doesn't work with lexical bindings enabled
Not super pretty, but better than completely broken :)
I'm open to suggestions if there are nicer ways to make this work with lexical bindings.
=> Fix haskell-ds-create-imenu-index to work properly in lexical binding mode

haskell-completions.el
I left the options in, since they might still be useful for people who want to enable dabbrev themselves. Honestly I think even if @geraldus there is not a good case for enabling dabbrev by default since it is not specific to haskell-mode. If people like it they can enable it themselves (in fact company-mode does this by default).
=> Use standard dabbrev completions for company mode

haskell-indentation.el
The "melpa-stable" release was correct, but I guess the recent
refactoring effort created a regression. The new version did a newline
before storing the current column/indentation. This means that <RET> 
would newline and be indented all the way at the left. This fixes
the behavior while following the new code style. (save column first,
then newline, then reindent)
=> Fixed `haskell-indentation-newline-and-indent`

doc/haskell-mode.texi, haskell-cabal.el, haskell-commands.el
New function `haskell-session-choose-target` enables choosing from available targets list from `.cabal` file.
It is just a wrapper around `haskell-session-change-target` which can still be used to select a target directly, by specifying it as an arg.
=> Choose a REPL session target from list

haskell-interactive-mode.el
The regex in `haskell-interactive-mode-trigger-compile-error` wouldn't match e.g. `<interactive>:6:1-2:`, preventing the rest of the function from running.
=> Fix `haskell-interactive-types-for-show-ambiguous'

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Disable layout rule only inside parentheses

haskell-compile.el
Useful for stack tool, which renders dependency-errors indented
Resolves #764
=> Skip space prefixes in error-messages

README.md
Previous instructions didn't work for me because they required `(require 'package)` to be inside `.emacs` first.
I propose going this "put this to your .emacs" route. Not sure if it's much better, but at least it should work for clean emacs out of the box, unlike previous instructions. Adding one more item to previous instructions to put "require 'package" seemed to make this "quick installation" too big.
What do you think?
=> Quick Installation

haskell-commands.el, haskell-compat.el
This fixes #863, whereby jumping to the definition of a symbol in the
same file was incorrectly activating the mark and region. This commit
also simplifies the original code, since the initial position marker can
simply be passed to xref-push-marker-stack. (The haskell-compat shim for
that function is also fixed here accordingly.)
=> Don't spuriously set mark on xref push

haskell-indentation.el, tests/haskell-indentation-tests.el
This is not syntactically legal Haskell:
main =
do putStrLn "X"
do putStrLn "X"
where this is:
main =
(do putStrLn "X")
(do putStrLn "X")
It parses but does not type check. Indentation should not propose the first case.
=> Keyword do is not open expression for indentation

haskell-indentation.el, tests/haskell-indentation-tests.el
Fixes #862. That is
let foo :: Int = 42
and
do foo :: Int <- return 42
=> Support scoped types in indentation

haskell-mode.el
Use a better way to check if the hoogle process is alive: Instead of
checking if the corresponding buffer-name is an alive process, store the
process handle in a global variable and check that.
The problem is that when using 'hoogle-lookup-from-local' without any
hoogle server running, a new local hoogle server is started, but the
code fails to recognize that server is running and instead repeatedly
reports that the server is not running offering to start it.
=> Fix hoogle lookup from local servers

haskell-mode.el
The fpcomplete hoogle service has been transferred to Stackage servers.
This patch makes sure that the hoogle query works with fpcomplete.
=> Fix hoogle query to fpcomplete

tests/haskell-indentation-tests.el
=> Expecting then

haskell-commands.el
Previously the responses to the startup commands could be delayed,
arriving so late that they appeared to be in response to later
commands (e.g. a :load).  By setting the prompt last, only one prompt
marker will be sent for the whole startup procedure.
Should fix issue #882.
=> Fix out-of-order session startup.

haskell-commands.el
With `haskell-process-reload-with-fbytecode` set to `t`, we first compile with object code, then switch to bytecode, touch the file and issue a `:reload`. However, if the `.o` file generated in the first compilation is still considered fresh -- because it has the same timestamp as the just-touched source file -- the reload doesn't do anything.
This patch makes the touch move the source code's timestamp into the near future, so that it's always newer than the object code. This way the reload will always recompile it. The mechanism is pretty ugly and a bit of a hack, but seems to work on Linux and OS X.
=> Ensure file reload when using -fbytecode

haskell-presentation-mode.el
This fixes a regression. `haskell-presentation-present` is supposed to pop-to-buffer when there is none and we're not in the buffer, and if we are inside the buffer it's supposed to re-use this same buffer. This fixes it. `(with-current-buffer ...)` confuses the value of `major-mode`.
=> Fix switching to the presentation buffer

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Support names starting with quotes

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Support `where` keyword after any expression

haskell-indentation.el, tests/haskell-indentation-tests.el
Fixes #894, fixes #323, fixes #907.
=> Implement QuasiQuotes syntax in indentation

haskell-indentation.el, tests/haskell-indentation-tests.el
Reference #916. One of those is fixed.
=> Toplevel indentation bugfixes for data, newtype, instance

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Navigate to top level declaration in indenatation

tests/haskell-indentation-tests.el
I added another test case which causes parse failure. It's quite complicated but couldn't reduce it further
=> Add rather baroque indentation test which cause parse failure

haskell.el
Currently nil is the argument for the buffer called in haskell-process-reload-file such that I always get "Haskell process command errored with: (wrong-type-argument stringp nil)" in the mini buffer.
=> Reloading: haskell-process-file-loadish needs the current buffer as an argument

haskell-indentation.el, tests/haskell-indentation-tests.el
This is an almost fix for #928.
=> Fix nested layout 1

haskell-cabal.el
`haskell-cabal-enum-targets` didn't filter out sections that were not targets
=> Filter only sections bearing targets - fixes #534

tests/haskell-indentation-tests.el
Also add one passing test for multiline tuples. It fails however with older haskell-mode so it makes sense to add it as regerssion test
=> Add failing tests for multiline string literals

tests/haskell-indentation-tests.el
=> Mark some indentation tests as passing

haskell-completions.el, tests/haskell-completions-tests.el
@geraldus: I improved your stuff a little.
=> Improve can grab prefix for completions

haskell-indentation.el, haskell-mode.el
=> Remove auto-fill code from indentation

haskell-indentation.el
haskell-indentation had the option to put overlay underlines at positions eligible as indentation points. This was supposed to help usability and debugging of indentation algorithm. It practice is was slow, distracting and a test suite helps development much better.
=> Remove dynamic indentation showing

haskell-indent.el, haskell-indentation.el, haskell-mode.el, haskell-simple-indent.el, tests/haskell-indentation-tests.el
=> Make haskell indentation the default indentation mode

haskell-indentation.el, tests/haskell-indentation-tests.el
Keep top level constructs like 'data', 'import', 'class', 'instance' at top level.
=> Recognize top level constructs in indentation

haskell-commands.el
As part of #592, commit 2b4e49cf modified this code to alter the global
value of tags-table-list as a side-effect, but this change was incorrect
and causes problems elsewhere.
Specifically, consider the following scenario:
- User tries to jump to a definition with haskell-mode-jump-to-def-or-tag
- That function falls back to haskell-mode-tag-find, which then calls
haskell-mode-jump-to-tag
This results in a call to haskell-process-generate-tags, which tries to
run hasktags, whether or not it is installed. As a side effect, the
global value of tags-table-list is set to include
"/project/root/dir/TAGS", which was probably not even created
properly (most people won't have hasktags installed).
Then, imagine we're working in an unrelated project, and use Emacs'
built-in completion-at-point …
=> Don't spuriously modify tags-table-list's global value

haskell-load.el
An example of an error message that gets triggered by this is the following
```
(All instance types must be of the form (T a1 ... an)
where a1 ... an are *distinct type variables*,
and each type variable appears at most once in the instance head.
Use FlexibleInstances if you want to disable this.)
```
=> Add an additional trigger for pragma suggestions

haskell-interactive-mode.el
When preparing multiline messages for the minibuffer, unwrap onto one line
and only truncate as much as necessary.  Previously, we showed the first
line and only a small part of the second.
closes #988
This does the right thing even with proportional fonts.  It should DTRT with wide chars and combining chars, but I haven't verified that.  
I looked at all the calls to `haskell-mode-message-line`, and I think it's reasonable to have them all use this new truncation behavior, but I'd appreciate someone double-checking that.
=> Truncate multi-line messages less aggressively

doc/haskell-mode.texi, haskell-mode.el, tests/haskell-mode-tests.el
Following discussion at https://github.com/haskell/haskell-mode/pull/961, I've tried to make the SCC functions (which I use) more pleasant to use and to maintain.  Please let me know if you want things done differently.
I wrote a new function to toggle SCC's, so only one keybinding is necessary.  I refactored the existing code to avoid spurious errors about "can't remove SCC" when adding an SCC.  I kept the old functions around for backwards compatibility, but I don't really care if they go away.
Along the way I found a bug, which I think I've fixed and adequately described in the commit messages.
=> Clean up SCC code

Makefile
This duplicate filename was throwing this warning:
Makefile:114: target 'check-haskell-cabal' given more than once in the same rule
=> Remove duplicate filename in Makefile

README.md
The space before the block-ending syntax throws off pandoc when converting to asciidoc.
=> Fix markup typo in README.md

haskell-indentation.el
Fixes #962. Fixes #985. Fixes #861. Fixes #970. Fixes #969.
Note that there is still a possibility to get an empty list of indentations, that fails indentations also.
=> Remove haskell-indentation-parse-error

haskell-commands.el, haskell.el
- Rename haskell-process-reload
- keybindings for -process-load-file & -process-reload
- remove references to -process-load-or-reload
- mark -process-load-or-reload obsolete
closes #807
=> Use haskell-process-load-file, not -load-or-reload

haskell-debug.el
I tried debugging a simple Haskell program in haskell-mode from spacemacs and got an error from this regex not matching. This change makes it work.
=> Add case for haskell-debug-parse-module regex to parse

haskell-customize.el, haskell-mode.el, haskell-modules.el
reuse `haskell-stylish-on-save` to decide whether to sort & align in `haskell-add-import`.
closes https://github.com/haskell/haskell-mode/issues/914
=> Do not sort imports twice

tests/haskell-indentation-tests.el
pull request for the failing testcase for bug #981 as discussed in the bug itself.
=> Failing testcase for bug #981: M-j to continue a comment on the next lines indents the next line

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Non-recursive haskell-indentation-phrase-rest

haskell-checkers.el
Otherwise, hlint will try checking files with names like '//home/foo/bar/Baz.hs/'.
=> Use vanilla buffer file name for hlint command

Makefile
=> Find Emacs once

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Support shallow indentation

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Case expression indentation fix

haskell-align-imports.el
If you have case-fold-search enabled and import a module named "Instance", haskell-align-imports-after-imports-p will stop looking as it  thinks it reached the end of the imports.
Changed regex to always be case sensitive.
=> Fix align imports for modules named "Instance"

haskell-commands.el
I added pure Haskell files and hsc2hs and c2hs files, since all of them contain mostly Haskell code.
But should Alex (\*.alex, \*.x) and/or Happy (\*.happy, \*.y, \*.ly) files be included? They always contain at least some user-defined Haskell functions, and it seems that searching for those should be possible with haskell-rgrep, but I'm not entirely sure. Any ideas?
=> Add some common extensions to haskell-rgrep

haskell-indentation.el
Seems it did not have any impact on anything.
=> Remove haskell-indentation-dyn-first-position

tests/haskell-indentation-tests.el
Includes a test case for #1044.
=> Cleanup tests with 'data' declaration indentation

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Record indentation should follow tibell style

haskell-mode-pkg.el
This way, haskell-mode shows up in `M-x package-list-packages`  when
filtering by the `haskell` tag
=> Define url and some keywords/tags for haskell-mode

haskell-font-lock.el, tests/haskell-font-lock-tests.el
=> Make quasi quote more visible

haskell-doc.el, haskell-font-lock.el
This PR rebases https://github.com/haskell/haskell-mode/pull/748 onto today's jmaster and removes the indentation changes, per discussion on that PR.
=> Add font lock type/data family declarations

README.md, doc/haskell-mode.texi, haskell.el
Here are a bunch of changes to the user manual to try to make it more closely reflect the actual code.  Feel free to cherry pick commits you like, and give me feedback on any that you don't want to merge as-is.
I have many more changes that I want to make, after some code diving to make sure I don't say anything untrue.
Am I right that the plan is to have the Texinfo be the main manual, not the Github wiki?
=> User manual updates

haskell-cabal.el, haskell-checkers.el, haskell-commands.el, haskell-completions.el, haskell-decl-scan.el, haskell-doc.el, haskell-mode.el, haskell-navigate-imports.el, haskell-process.el, haskell-sandbox.el, haskell-session.el, haskell-string.el, haskell-utils.el, w3m-haddock.el
In a couple of places I fixed obviously outdated docstrings, as well.
=> Fix typos in documentation strings

doc/haskell-mode.texi, haskell.el
Instead of recommending this binding in the manual, provide it by
default, and document that it the manual.
This follows my understanding of https://github.com/haskell/haskell-mode/wiki/Complete-functionality
What's the recommended way to test functions that inspect the filesystem?  `el-mock`?  Some other mocking library?
=> Add keybinding for `haskell-cabal-visit-file`

tests/haskell-font-lock-tests.el
Tests #1066 which fixes #1057. The test succeeds.
I tried to follow the conventions that I could find, but if you want me to move the test up in the file, rename it, or make any other change, let me know.
=> Add test for 'type role' font-lock

tests/haskell-font-lock-tests.el
More font-lock tests, as requested in #1068.
=> More font lock tests

haskell-interactive-mode.el, tests/interactive-haskell-mode-tests.el
This supercedes https://github.com/haskell/haskell-mode/pull/636
The regexp is the same as that PR; my commit adds a few tests.
=> Disallow leading spaces in error regexp in interactive mode

haskell-package.el
`haskell-package`'s slots were not defined, and that was creating a
byte-compiler warning that the lexical variable `pkg` was unused.
I made this commit just to shut up the byte-compiler (honestly, I just started using this mode). 
As an aside, am I missing something, or is the struct not actually used? The `haskell-package-get*` functions use `haskell-package-parse` to create the struct, but nothing seems to actually use the result (I'm not sure how something could without the slots defined).
=> Define haskell-package struct's slots

tests/haskell-utils-tests.el
Don't merge yet!
@gracjan I have no strong opinion on `type-at-command-composition` test.  It looks very silly and feels like testing function's logic reimplementation.  Maybe there are some other aspects we'd better to test?
I will add few other tests in few days.
Also, maybe it's better to move prettification stuff, e.g. comments, indentation, to another PR?
=> Utils coverage

haskell-utils.el, tests/haskell-utils-tests.el
=> Improve haskell-utils-reduce-string. Add tests

Makefile, tests/haskell-font-lock-tests.el, tests/haskell-indentation-tests.el, tests/haskell-test-utils.el, tests/haskell-utils-tests.el
If everything is good then ready to be merged
=> Test utils

tests/haskell-utils-tests.el
Don't merge yet, I opened this to see coverage stats first.
@gracjan I've spent few hour trying to make it record changes to flag during ert running test. I have tried `command-execute`, `call-interactively`, `execute-kbd-macro`, and changing modes but flag remains empty all the time. Can you help me with this?
=> Add post-command-hook related tests

haskell-cabal.el, tests/haskell-cabal-tests.el
Addresses #1094: when calling `haskell-cabal-subsection-arrange-lines`
on a Cabal section, only separate the lines in the section by commas
when the section was already comma-separated. Ignore commas in strings
or comments.
=> Follow comma style when arranging a Cabal section

haskell-cabal.el, tests/haskell-cabal-tests.el
As discussed in #1094. See the commit messages for more info.
=> Detect comma style

.travis.yml, Makefile, README.md, doc/haskell-mode.texi, haskell-mode-pkg.el, haskell-mode.el
Fixes #847.
Note that we will merge this one after nearest melpa stable release.
=> Require at least Emacs 24.1

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Honor equals on its own line in data decl

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Honor equals on separate line after guards

doc/haskell-mode.texi, haskell-load.el, haskell.el, tests/haskell-load-tests.el
Supercedes https://github.com/haskell/haskell-mode/pull/818
=> Implement haskell-goto-first-error

haskell-process.el
=> Allow haskell-process-path-* to be lists.

haskell-interactive-mode.el
The completion of the same candidate may yield different results due to the
state of the repl. (e.g :cd)
Fixes #1113
=> Remove haskell-interactive-mode-completion-cache

haskell-cabal.el, haskell-commands.el, haskell-debug.el, haskell-doc.el, haskell-hoogle.el, haskell-interactive-mode.el, haskell-load.el, haskell-mode.el, haskell.el, tests/haskell-doc-tests.el
=> Prevent haskell-doc-mode to hang Emacs during user input waiting

haskell-interactive-mode.el, tests/interactive-haskell-mode-tests.el
Do not leave blank line when removing import statement.
Now covers multiline imports properly when remove or comment out option
selected.
Will think about some test, don't merge yet.
Fixes #1109
=> Remove suggested imports completely

haskell-load.el, haskell-process.el
=> Use condition-case-unless-debug

tests/haskell-indentation-tests.el
This adds two tests for indenting simple data type definitions.  I didn't entirely understand the numbering scheme, so I just made an educated guess and added them at the end.  If that's wrong, let me know and I can fix it.
See #1125 for a brief explanation.
=> Add indentation tests for constructor and deriving

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Align data declaration contructors in indentation

doc/haskell-mode.texi, haskell-customize.el
=> Docstrings and documentation for haskell-process-path-*.

haskell-mode.el, haskell.el
Fixes #1074. Fixes #788. Fixes #256.
=> Stylish haskell after save

haskell-interactive-mode.el
This sets a variable with the source buffer so we can switch back.
This is pretty bizzare, though.  Both before and after this commit,
`haskell-session-interactive-buffer` switches to the buffer if it's
newly created, but if the buffer already exists, just returns the buffer
without visiting.  This function shouldn't switch, and callers
should decide if they want to switch.
closes #955
=> Use `haskell-interactive-switch` in process-load

haskell-interactive-mode.el
This makes it so that you can't insert new text inside read-only text.
This doesn't feel like the best way of doing it (namely the prompt-specific part), but the other ways that I could think of would need an overhaul of the system or they resulted in surprisingly hard to debug errors, so I just settled on this.
The main reason for this is to prevent people from inserting behind the read-only space at the end of the default prompt and wondering why they can't hit RET to evaluate their input (which happened to me enough times).
=> Add front-sticky property to read-only text in REPL

haskell-compile.el, haskell-doc.el, haskell-font-lock.el, haskell-mode.el
The comment by `compilation-filter-start` says it was available since 24.2, but the 24.1 NEWS files says it was added then, so it's a safe deletion.
=> Remove some outdated code

haskell-debug.el, haskell-indent.el, haskell-indentation.el, haskell-interactive-mode.el, haskell-menu.el, haskell-mode.el, haskell-presentation-mode.el, haskell.el, inf-haskell.el
=> Make keymap definition more consistent

Makefile, haskell-commands.el, haskell-compat.el
After removing support for Emacs 23 haskell-compat.el can loose some
weight.
=> Cleanup haskell-compat.el

haskell-mode.el, tests/haskell-mode-tests.el
Added a basic test for #1148. Turned out simpler than I thought ;)
=> Add test for forward-sexp-function

haskell-cabal.el, tests/haskell-cabal-tests.el
In `haskell-cabal-mode` with the point indicated with the vertical bar below, `forward-char` should leave the point after `Some` instead of after `Type`.
```haskell
Exposed-Modules:   |Some.Internal.Type
```
This was caused by the following line:
```emacs-lisp
(modify-syntax-entry ?. "w"  st)
```
Which makes "." a word constituent instead of a punctuation character. This was added in aa970092a1e812ff78af2c1d65484b4281ce2234, "merge caballero with haskell-cabal". The fix: remove the line above.
=> Fix #1146 by treating . as punctuation

haskell-mode.el, tests/haskell-mode-tests.el
I implemented the backward case, basically according to your hints in #759. The main difference is that I do not skip back to whitespace, but use plain `backward-sexp`, which also properly skips over parens.
=> Implement backward case in haskell-forward-sexp

haskell-font-lock.el, haskell-mode.el, tests/haskell-font-lock-tests.el, tests/haskell-lexeme-tests.el
=> Improve font-lock

haskell-repl.el
This creates a new prompt that doesn't affect the history or send
any information to the GHCi process. This only occurs when on the
same line as the last prompt.
This makes the REPL more like the others you'd find in Emacs, and also more like GHCi itself.
=> Make RET in REPL create new prompt with blank input

haskell-hoogle.el
Read the `haskell-hoogle-command` variable before switching to the help window which removes the buffer local `haskell-hoogle-command` from the scope.
In other words: This is a tiny change, I just extracted the command text into a variable defined outside the context of the new buffer so that the right buffer local `haskell-hoogle-command` is used.
=> Fix haskell-hoogle to work with buffer local var

haskell-completions.el, haskell-interactive-mode.el, haskell-mode.el, haskell.el
=> Support simple completions in non-interactive context.  Support keyword completions 

haskell-commands.el
As discussed on IRC.
As the windows version didn't include a find not applied there, and i have no windows environment to test on.
=> Ignore stack and cabal files from hasktags

haskell-interactive-mode.el, haskell.el
This change lets you press Enter on a line in a haskell-interactive session to copy that line to the current prompt. It is a small change to make the lack of history-search (e.g. #315) slightly less painful.
In #315 Ivan suggested: "If nothing else, inf-haskell let you C-r to do a backward search in the buffer, and then hitting Enter would copy that line to the current prompt line." That's essentially what I've done.
I'm only an inexpert Emacs Lisper, so any corrections or improvements are welcome!
=> Add haskell-interactive-copy-to-prompt.

doc/haskell-mode.texi, haskell-indentation.el, haskell-mode.el, haskell.el
=> Remove obsolete code

haskell-indentation.el
This should help with smartparens and other modes that expect
indent-region-function to do something sensible. Currently doing nothing
is better than what was in there.
We still do not have a meaningful indent region function that preserves
semantic meaning of a program.
Reference #796, #1032.
=> Make haskell-indent-region do nothing

haskell-mode.el, tests/haskell-indentation-tests.el
See #1189. Since the insides of quasiquotes are regarded as ordinary characters now, `\s"` no longer stumbles on `"`s inside quasiquotes.
=> Treat insides of quasiquotes as strings

haskell-customize.el, haskell-interactive-mode.el, haskell-process.el, haskell.el
1) `haskell-interactive-kill` was added to the global hook instead of
the local hook.
2) Typo: `haskell-process-end-hook` was used instead of
`haskell-process-ended-hook`
3) Rename `haskell-process-ended-hook` to
`haskell-process-ended-functions` as per
https://www.gnu.org/software/emacs/manual/html_node/emacs/Hooks.html
=> Change a couple hook properties

haskell-indentation.el, haskell-interactive-mode.el, haskell.el
This fixes a few warnings Flycheck was showing.
=> Fix some warnings

haskell-completions.el, haskell-process.el, haskell-utils.el
As a user of company mode I see errors in mini-buffer very often:
> Company: An error occurred in auto-begin
> Wrong type argument: stringp, nil
Small investigation lead me to proposed changes
=> Small improvements of completion functions

haskell-c2hs.el, haskell-utils.el, tests/haskell-c2hs-tests.el, tests/haskell-font-lock-tests.el, tests/haskell-test-utils.el
This is a wrapper around haskell-mode, that mostly adds fontification for {#...#} blocks.
=> Add c2hs mode

haskell-cabal.el
Define removed functions as aliases and mark them as obsolete.
This should fix https://github.com/flycheck/flycheck-haskell/issues/54
=> Return removed names for backward compatibility

haskell-cabal.el, haskell-debug.el, haskell-doc.el, haskell-hoogle.el, haskell-interactive-mode.el, haskell-load.el, haskell-mode.el, haskell-utils.el, tests/haskell-doc-tests.el
We have a circular dependency `haskell-mode` ⟷ `haskell-cabal` now.  Looks like that the only thing required in `haskell-cabal` from `haskell-mode` is `haskell-mode-toggle-interactive-prompt-state` function.  To resolve circular dependency I moved this function to Utils module.
=> Move haskell-interactive-prompt-state related definitions to haskell-utils.el

haskell-cabal.el, haskell-commands.el, haskell-interactive-mode.el, haskell-load.el, haskell-mode.el, haskell.el
=> Invoke hasktags more directly

haskell-completions.el
Related #1184 
I thought to add `tags-completion-at-point-function` to `completion-at-point-functions` hook at first, but this approach is not good enough because in this case completion functions are run sequentially and candidates are not merged.  So, if haskell completion function will go first and it is able to complete thing at point there is no candidates from tags and vice versa.  And it is not clear what function should go first.
Fortunately, I've discovered `tags-completion-table` function, with it now it's possible to merge tags completions with keyword completions.
One question: should we revisit tags table automatically when it is regenerated (in `haskell-mode-generate-tags`)?
=> Extend static completions with candidates from tags table

doc/haskell-mode.texi
@gracjan I want to add «Tags» section (looks like there nothing about tags in docs!), but do not know:
+ what is the best place for it
+ and how to make a hyperlink to that section
Related #1184
=> Update completion section

doc/haskell-mode.texi
Should fix #1230, related #1172 #1184
=> Small docs improvements

haskell-mode.el, tests/haskell-completions-tests.el, tests/haskell-mode-tests.el
Let's see will it pass the tests.  I think I can add some tests for operators too.
=> Handle operators in haskell-ident-pos-at-point too

inf-haskell.el
=> Use plain syntax in inferior-haskell-send-decl-post-filter

haskell-font-lock.el, haskell-lexeme.el, haskell-mode.el, tests/haskell-c2hs-tests.el, tests/haskell-font-lock-tests.el, tests/haskell-test-utils.el
=> Font lock types in their own color

haskell-completions.el
GHCi prior to version 8.0.1 have bug in `:complete` command: when completing operators it returns a list of all imported identifiers (see Track [ticket](https://ghc.haskell.org/trac/ghc/ticket/10576)).  This leads to significant Emacs slowdown.  To aviod slowdown operator completions are disabled for now.
=> Disable interactive operator completions

haskell-cabal.el, haskell-doc.el
=> Remove final cl requires

haskell-font-lock.el, tests/haskell-font-lock-tests.el
=> Use default face in quasi quotes

doc/haskell-mode.texi
=> Document indent-region as a no-op

haskell-indentation.el, tests/haskell-indentation-tests.el
Fixes #1046, fixes #1154.
Also fixes other issues with deriving keyword in `data ...=` and `data ... where`.
=> Implement standalone deriving indentation

haskell-indentation.el, tests/haskell-indentation-tests.el
Fixes #1197, fixes #1270, fixes #1084.
=> Simplify haskell-indentation-phrase-rest

haskell-repl.el
Gets rid of a check that was made redundant in a previous PR (GH-457).
=> Simplify haskell-interactive-handle-expr

haskell-indentation.el, tests/haskell-indentation-tests.el
Fixes #1178, fixes #1291, among some other things.
=> Allow more indentation positions in haskell-indentation

haskell.el
Also force users to input a valid key (or quit).
Closes #1272
=> Put cursor in the echo area at prompt restart

haskell-load.el, tests/haskell-load-tests.el
To see the failure, start a fresh copy of emacs, load a .cabal file, M-x
haskell-process-cabal-build; while the logic in haskell-process-do-cabal
suggests that that should not require an interactive process, it
complains that there is no interactive process.
I suspect this has been broken for a while (perhaps always).  The
failure stems from the fact that (haskell-interactive-process) throws an
uncaught error if there is no interacive process, which aborts the
function.  If that is wrapped to mask the error, (process-status child)
also throws an uncaught error, which aborts the function.
Thus the direct cabal invocation code would never be reached.
This is the least intrusive fix I can see---wrapping both calls
with (ignore-errors), and not even checking (process-status) if we don't
have …
=> Fix logic for running cabal directly.

haskell-indentation.el
This part of code is (almost) impossible to reach because
(= haskell-indentation-layout-offset current-indent)
mixes up absolute and relative positioning and triggers only if
current-indent is haskell-indentation-layout-offset from left margin.
Usually it is more indented.
This code cleary was meant to do something, but I'm not sure what.
=> Remove unreachable clause in indentation

doc/haskell-mode.texi, haskell-indentation.el
This does it like in `cc-mode'.
Also, I removed a few unnecessary things in the minor mode definition and removed an unused variable (Fixes #1294).
Closes #1133
=> Implement electric characters

doc/deploy-manual.sh
=> Improve manual deployment script

haskell-mode.el, tests/haskell-mode-tests.el
It was disabled in 96c8bbfb37c237415a14c7d616681cb8d9681eb4 because
`haskell-adaptive-fill` didn't work well. However, the default adaptive
fill rulles play nicely with Haskell, so it's pretty useful to keep it
enabled even without a custom adaptive-fill-function.
=> Enable adaptive-fill-mode

haskell-font-lock.el, tests/haskell-font-lock-tests.el
=> Add LiquidHaskell annotation highlight

haskell-commands.el
(message fmt ...) first argument is treated as format and %-signs are format signs.
=> Fix spurious uses of message

haskell-doc.el
=> Fix typo in haskell-process-get-type

haskell-commands.el
The function name & docs suggest this is the intended behavior.
`haskell-mode-find-def` errors if there is no session, so we need to
only call it if there is a session.
closes https://github.com/haskell/haskell-mode/issues/1180
See discussion in https://github.com/haskell/haskell-mode/pull/1326
=> Fallback to tags if there is no haskell-session

haskell-cabal.el, tests/haskell-exec-tests.el, tests/haskell-mode-tests.el, tests/haskell-test-utils.el
Add a way to substitute paths for tools. Add directory structure creator.
Implement hasktags tests.
Fixes #1206.
=> Improve external tool testing

tests/haskell-font-lock-tests.el
I wrote tests for the font lock issues with the `pattern` keyword, as discussed in #1313.
Please check if the way I used `check-properties` is correct, since:
* It wasn't entirely clear but it seemed like the triplets in the second argument of `check-properties` each describe the fact that a token should be fontified a particular way in all the test strings given in the first argument (the alternative interpretation is that the triplets describe a series of fontifications for each token in order, and since none of the existing tests duplicate the first element of a triple, it's ambiguous which it is).
* I gave `t` as the second element of each triple, which I am not sure about either. This element is the "syntax" of the token, but I don't know enough about Emacs fontification to know what …
=> Added font lock tests for pattern synonyms (for #1313)

haskell-decl-scan.el, tests/haskell-decl-scan-tests.el
In other emacs modes, `C-M-e` will go just past the end of the current function rather than to the beginning of the next function.  Here is a patch that makes this work correctly for `haskell-decl-scan-mode`.
=> Going forward defun should go to end of defun

haskell-font-lock.el, tests/haskell-font-lock-tests.el
=> Properly detect underscore and apostrophe in declarations

haskell-font-lock.el, tests/haskell-font-lock-tests.el
=> Track parens ourselves in type highlight

doc/haskell-mode.texi, haskell-commands.el, haskell-customize.el, haskell-interactive-mode.el, haskell-repl.el
There's a couple oddities still left, but I think this should improve the state of multi-line support in the REPL.
* Adds a custom variable for prompt2 (multi-line prompt)
* Highlights prompt2 when inside a multi-line block or in `:set +m`
* haskell-interactive-mode-multi-line properly indents the multi-line expression (strips off whitespace in later lines)
* `C-j` indents a bit more like you'd expect
Fixes #915 
Fixes #1278
=> prompt2 support and multi-line

Makefile
Produces correct autoloads when the source tree has been symlinked. If the source tree is a symlink, `CURDIR` will always be the dereferenced path, while `PWD` is usually what we expect. Using `CURDIR` can lead to some incorrect paths in `haskell-mode-autoloads.el`.
I noticed this when trying to build a haskell-mode source tree that had been symlinked from another directory (I use GNU Stow to symlink things from a git repo):
```
[tim@axiom:~] % ls -alr ~/.emacs.d/haskell-mode
lrwxr-xr-x  1 tim  staff  40 21 May 23:31 /Users/tim/.emacs.d/haskell-mode -> ../src/emacs/emacs/.emacs.d/haskell-mode
```
During `cd ~/.emacs.d/haskell-mode && make`, the following are true:
```
CURDIR=/Users/tim/src/emacs/emacs/.emacs.d/haskell-mode
PWD=/Users/tim/.emacs.d/haskell-mode
```
... and this leads to …
=> Use PWD instead of CURDIR in Makefile

haskell-indent.el
It seemed to me when reading the documentation that the `haskell-indent-hook` note refered to the argument, so document it separately
=> Document `defun haskell-indent-mode`'s arg

tests/haskell-decl-scan-tests.el
There was a typo that I made last time around.
=> Fix documentation in haskell-decl-scan-tests.el

tests/haskell-decl-scan-tests.el
Fixup my tests in `haskell-decl-span-tests.el`
=> Test cursor using `{b,e}obp` and add checks for this

haskell-decl-scan.el, tests/haskell-decl-scan-tests.el
I don't know how to write a test for this because it requires the buffer to be fontified, and I don't know how to do that in batch mode.
```
module Test where
{- documentation here -}
fun = 13
{- document this function -}
f = 23
```
This patch makes going forward defuns (`C-M-e`) correctly go over comments.
`M-< C-M-e` gets you to line 2, `C-M-e` again gets you to line 5, `C-M-e` again gets you to line 8.
Before it would take you to lines 4, 7, and 8, respectively.
=> Make going forward defun work correctly with comments

haskell-interactive-mode.el
If user pastes something into a multiline expr, the lines won't have
the initial prompt2, so try to avoid removing them in that case
(I was looking at https://github.com/haskell/haskell-mode/issues/608 and wondering if I could make a quick hack by simply sending defun-at-point as a multiline expression, but it seems to require quite a lot of fiddling with indentation, seems like something that should be built-in to ghci rather …)
=> allow pasting into multiline expressions

haskell-mode.el
In #1375, `haskell-guess-module-name` was renamed to
`haskell-guess-module-name-from-file-name` which caused breakage for
users of the original function name. Fix the breakage by defining an
alias that makes the original name point to the new function name.
=> Add an alias to fix the breakage of #1375

haskell-mode.el
Map haskell-mode-format-imports to C-c C-, to avoid conflict with haskell-indent
Fixes #396.
=> Map haskell-mode-format-imports to C-c C-,

inf-haskell.el
GHC 8.0 uses an error message of the form
```
/home/alanz/mysrc/github/alanz/ghc-exactprint/tests/Test.hs:99:3: warning: [-Wunused-matches]
Defined but not used: ‘prettyRoundTripTests’
```
The word "warning" no longer has an initial capital letter.
=> Fix inferior-haskell warning font lock for GHC 8.0

haskell-font-lock.el, tests/haskell-font-lock-tests.el
=> Support pattern as keyword

doc/haskell-mode.texi
PR #1403 changed the code but the manual was not updated.
=> Fix documentation of haskell-mode-format-imports key binding

haskell-lexeme.el, haskell-process.el
Current emacs fails to build with some errors on unused lexical variables.  
As the complaint seems legitimately, I removed them.
Fixes #1428.
=> Removed unused lexical variables.

haskell-customize.el, haskell-interactive-mode.el
The point was forcibly moved to (point-max) in each instance, which
seems to defeat the purpose of this function.
Now the point is only moved to (point-max) when this variable is
non-nil. To keep the default behaviour the same, the default value of
this variable is now t.
Fixes #1438.
=> Fix usage of haskell-interactive-mode-scroll-to-bottom

haskell-commands.el, haskell-customize.el, haskell-interactive-mode.el, haskell.el
=> Scroll in haskell-interactive-mode only when at correct positions

haskell-customize.el, haskell-interactive-mode.el
Text that was explicitly documented as read-only is still
unconditionally read-only.
Fixes #1437.
=> Make most interactive text optionally writable

ghci-script-mode.el
Commit ee5effd110cd0f23d36cc391fbba767816dfc83b removed the function
from haskell-mode.el but missed this reference.
=> Remove reference to haskell-mode-suggest-indent-choice.

haskell-load.el
The message GHC gives is
Illegal view pattern:  identity -> x
Use ViewPatterns to enable view patterns
which until now wasn't caught by haskell-mode.
=> Detect and autosuggest ViewPatterns

haskell-decl-scan.el
This simplifies the code, making it consistent and readable.
=> Use functions `bobp' and `member' instead of manual implementations.

haskell-decl-scan.el, tests/haskell-decl-scan-tests.el
This will fix edge cases in haskell-ds-forward-decl that would cause it to go forward to the beginning of the next decl when there are documentation comments, rather than the correct behavior of going to the end of the current declaration.
Behavior demonstrated (cursor is at POINTBEFORE at the beginning and should go to NEWPOINTAFTER, used to go to POINTAFTER).
POINTBEFOREmain = x
NEWPOINTAFTER
-- | Documentation
POINTAFTERx = return ()
=> Recognize documentation comments as comments

haskell-decl-scan.el
Extract whitespace check to a separate function.  In a future pull I will make, it requires this commit.
=> Extract whitespace check to separate function

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Support foreign import in indentation

haskell-customize.el
This option has been renamed to `--ghci-options`:
https://github.com/commercialhaskell/stack/commit/3348ec867bb339ff5f525f68f2e40248d5bfedce#diff-36766742aefd855fe3d2063edae89117
I notice there has been discussion about this (#1455). Can we consider changing the default instead of everyone fixing on their own? After all the change was more than one year old.
=> Fix stack-ghci invocation argument

haskell-presentation-mode.el
Makes it so that the point is at the beginning of any the new information added. This simplifies for example copying a type signature after `haskell-process-do-type`.
=> Point at new info in haskell-presentation-present

haskell-interactive-mode.el
haskell-session-interactive-buffer: Format specifier doesn’t match argument type
=> Fix error in haskell-session-interactive-buffer

haskell-lexeme.el, haskell-mode.el
Accommodate that in Parser.y '{-# INLINE' is a literal that breaks brace
matching unless brace is considered inside a string.
=> Extend what is matched as char literals

haskell-cabal.el, haskell-commands.el, tests/haskell-cabal-tests.el
This is an initial attempt at addressing issue #1187. Please let me know if there's a better way, this is my first outing into the haskell-mode code.
=> Generate 'stack' tool style compilation targets.

haskell-cabal.el, tests/haskell-cabal-tests.el
Changes sorting of dependencies so "base" appears at the type of the list.
E.g. instead of 
```
build-depends: aeson
, base >= 4.8 && < 5
, text
```
we have
```
build-depends: base >= 4.8 && < 5
, aeson
, text
```
=> Make haskell-cabal-subsection-arrange-lines sort base before other packages in build-depends

haskell-customize.el
One step further towards fixing https://github.com/haskell/haskell-mode/issues/1433.
=> make cabal-new-repl a legitimate process type

haskell-commands.el
Adds `haskell-interactive-set-+c` defcustom to switch whether option is added to ghci invocation, and updates error msg on type-at failure. For #1436
=> Add defcustom for :set +c

.gitignore
build-* is created when we build the project, it would be helpful if it were in the `.gitignore` file because we don't need it.
=> added build-* dir to gitignore

haskell-font-lock.el
I was getting a lot of `error in process filter: Wrong type argument: number-or-marker-p, nil` errors and tracked it to this function.  `.` can appear as the first character of the buffer, so the logic was falling over a touch.
Fixes #1497
=> haskell-font-lock-dot-is-not-composition fix

.travis.yml, appveyor.yml, emacs-24/Dockerfile, emacs-25/Dockerfile, emacs-snapshot/Dockerfile
+ In travis:
- We use docker, so it is very flexible to choose distributions etc.
- Emacs24
- Emacs25
- Emacs26 / snapshot
- GHC 8.0.2
+ Appveyor:
- Emacs24
- Emacs25
- GHC 8.0.2
=> Improved travis, appveyor build mechanism

haskell-customize.el
+ Some defcustoms were added to the PR #1543 that are not necessary. These defcustoms were added with the assumption that PR #1545 will be merged. Since that PR #1545 is a little controversial, these defcustoms are not needed and can be safely removed.
=> removed unwanted defcustoms

doc/haskell-mode.texi
Added key bindings for compilation mode. We could Just link to the [GNU documentation](https://www.gnu.org/software/emacs/manual/html_node/emacs/Compilation-Mode.html#Compilation-Mode) or Merge this PR.
=> Compilation buffer keybindings

haskell-load.el
At some point by GHC 8.2.1, the text for successful load of a module
into ghci changed. This patch allows for the new format, in addition
to the existing ones.
=> Fix haskell-process-load-complete for GHC 8.2.1

haskell-customize.el, haskell-load.el
When using haskell-interactive-mode's REPL support in environments that already have in-buffer flycheck support (e.g. `intero', `dante'), the redundant overlays become problematic and confusing for users. This commit adds a customization option to suppress haskell-mode's overlays so that users with such set-ups can choose to see only their flycheck errors.
Submitting this as a PR for visibility, but will assume this is okay to merge in a day or two if no other maintainers have an objection, since it seems fairly uncontroversial.
=> Provide customization option `haskell-process-show-overlays'

haskell-customize.el, haskell-mode.el
The variables actually used to customize indentation are
`haskell-indentation-*-offset`.
=> remove unused variable `haskell-indent-spaces`

emacs-24/Dockerfile
There isn't any emacs24 on later versions of ubuntu
=> limit ubuntu to zesty for emacs24

haskell-commands.el
I have come with similar use case as in #651
I just want to be able to see the `stylish-haskell` stderr because it could fail with errors like:
```
stylish-haskell: Language.Haskell.Stylish.Editor.applyChanges: refusing to make overlapping changes on lines 59-60, 59-60
CallStack (from HasCallStack):
error, called at lib/Language/Haskell/Stylish/Editor.hs:46:28 in stylish-haskell-0.8.1.0-Dqoruy2bCD1Kn6ytiOdLeZ:Language.Haskell.Stylish.Editor
```
59-60 lines in my code:
> Declaration uses unicodeSyntax but it is not consistent: `... Integer -> IO ...`
``` haskell
getLimitedRange ∷ Integer → Maybe Integer → Maybe Integer -> IO (UTCTime, UTCTime)
getLimitedRange limit fromTime toTime = do ...
```
This kind of errors is not covered by flycheck and running `stylish-haskell File.hs` every time I …
=> Log stderr into separate buffer

haskell-load.el
ghc 8.2 reports only a number of loaded modules https://github.com/haskell/haskell-mode/commit/eac5567e2a47be1272ed73b19c43025a457fa416
=> fix `haskell-process-extract-modules' for ghc 8.2

haskell-customize.el
Remove `:safe 'functionp` from the definition of the `haskell-process-wrapper-function` Customize variable.  
Marking values which validate `functionp` as "safe" meant that any file could potentially execute any code on the Emacs instance it's been open.  This commit removes this possibility.  
Thanks!
=> [security] Don't make functions safe file-local values

haskell-completions.el, haskell-font-lock.el, haskell-indent.el, haskell-indentation.el, haskell-mode.el
This adds font-lock, indentation and recognition for GHCs Backpack signatures. @purcell
=> Add support for `signature`s and .hsig files

haskell-compile.el
follow up to #1608 (ansi colours included in this screenshot to show them playing well together)
Note that `next-error` (i.e. jump to error) works as expected... and everything you see that is underlined is clickable, if you are so inclined as to use something as clumsy as a mouse :stuck_out_tongue_closed_eyes:
=> failed tasty tests are errors

haskell-load.el
fix https://github.com/haskell/haskell-mode/issues/1496
https://github.com/haskell/haskell-mode/issues/1553
=> Update haskell-load.el (fix  "Unexpected response from haskell process")

inf-haskell.el
If I give arguments to haskell-process-path-ghci run-haskell fails with an error.
=> Fix error when haskell-process-path-ghci has arguments

doc/haskell-mode.texi, haskell-repl.el, haskell-svg.el
When working on SVG images, it's sometimes useful to see them directly as the REPL output within Emacs.
=> Add display of SVG images in REPL.

haskell-compile.el
For example, when tasty is called with `--color=always` // @feuerbach
Disabled by default to avoid any performance impact, but perhaps we can do a test cycle and if people like it maybe turn it on by default?
BTW, I think there is a bug in Emacs... I had to use `(point-max)` but the docs said `(point)` should work.
=> support ANSI colours in the compilation buffer

haskell-load.el
@gregorycollins suggested this on #1605, which fixes #1553 for the case where no modules are loaded.
=> Fix loading for GHC 8.4, suggested by gregorycollins

haskell-font-lock.el
This PR introduces three keywords used in deriving clauses
=> introduce `anyclass`, `stock` and `via` keywords

haskell-mode.el
haskell-indentation-mode is already loaded by default in the
haskell-mode-hook.  By forcing it to load every time haskell-mode loads,
the user can disable it only by toggling it off again; removing
haskell-indentation-mode from haskell-mode-hook will have no effect.
=> Remove extra loading of haskell-indentation-mode

haskell-lexeme.el, tests/haskell-lexeme-tests.el
This PR fixes issue https://github.com/haskell/haskell-mode/issues/1615. Another related issue (now resolved) is https://github.com/haskell/haskell-mode/issues/1615. The character lexeme regex does not take into account the single colon character, which caused haskell-mode to interpret it as the type operator `':` (enabled with `DataKinds` and `TypeOperators`). This generally did not cause any issues, however in my case (in a parsing function), if `':'` was followed by a closed paren it confused the lexer and caused the rest of the lines to be indented the wrong way (also notice the red closing quote):
=> Fix lexer to read ':' as character

haskell-cabal.el
Fixes #1627.
This is mostly an update to the keywords used for highlighting, but there is also a command and a keybinding for consistency with the rest of the mode.
One thing to be aware of: <kbd>M-g c</kbd> is typically bound to `goto-char`, and this shadows that binding in `haskell-cabal-mode`. I think that the consistency with the other commands in this mode is more important that this very-rarely-used binding, but that's a judgment call. I'm happy to remove that default binding if you'd like.
=> haskell-cabal-mode: Add support for common-stanzas

haskell-load.el
Looks like there was similar fix for successful modules load with GHC 8.4 (commit e6169a6597c79e53aa3632c8455c5ba10fa2ba74). I've just upgraded to 8.6.3 and struggled with it's output. Found out that it sometimes says "Failed, five modules loaded.". Respective fix attached.
=> Fix for "Unexpected output.." when modules load failed on GHC 8.6.3

haskell-hoogle.el
I use it like this:
```
(setq haskell-hoogle-server-command (lambda (port) (apply haskell-process-wrapper-function (list (list "hoogle" "server" "--local" "-p" (number-to-string port))))))
```
to launch my hoogle in a nix-shell.
=> Allow user to provide custom hoogle server command

haskell-string.el
This messes up minibuffer editing when active. We only want a message
to show up when there is no active minibuffer window.
/cc @purcell
=> Don’t show message when minibuffer is active

haskell-cabal.el
Previously, cabal-mode indented to the ":" column of a subsection in a
cabal file. This was not how most users indented their .cabal files
and was surprising. Instead of doing this, we indent relatively to the
first entry in a subsection list. When it doesn’t exist, use the old
behavior.
:data-indent-column is added to store this new indent level. It needs
to be separate from :data-start-column due to :data-start-colum also
being used in finding the start of a subsection heading.
/cc @purcell
=> Handle cabal indentation relative to first line

haskell-customize.el
I have GHC installed only by Stack.
GHC alone is not installed.
I'm afraid of conflicts because I'm using Gentoo and it takes time to compile GHC.
In that environment, `switch-to-haskell` doesn't work in the global space.
This is because `haskell-process-type` only runs `stack ghci` in a Stack project.
Actually `stack ghci` can operate in global space.
This will not break the behavior of those who want to use a single ghci for the final fallback.
=> added: stack ghci fallback when `(eq 'auto haskell-process-type)`

haskell-commands.el, haskell-session.el
Two main changes from this (apart from a little bit of code cleanup):
1. Can now get the list of targets from `stack ide targets`, which should help in multi-package projects
2. When starting a session, the prompt of available targets is presented as well (rather than having to remember them or using the default, the latter of which fails in the case of a package having the same name as an executable)
=> Better targets

inf-haskell.el
```haskell-program-name-with-args``` uses ```nconc``` with quoted lists, which leads to infinite lists on repeated calls [1]. 
[1] [Elisp manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Rearrangement.html)
=> Fix haskell-program-name-with-args

doc/haskell-mode.texi
A clarification in the manual to obtain SVG rendering at the GHCi REPL.
=> Improve manual description to obtain SVG rendering at the GHCi REPL

haskell-compile.el
It is currently checking for the prefix to be a negative integer, which throws a compiler error because we are checking for it to be a `'-` in other places. Looks like this error is introduced in b8892291c0e44f964dc1634351e62b1b242d55f7 commit. This PR reverts it to the earlier behaviour.
=> Fix haskell-compile.el

haskell-font-lock.el, haskell-lexeme.el, tests/haskell-font-lock-tests.el, tests/haskell-lexeme-tests.el
This enables font-locking when the quasiquoter name is imported qualified, e.g.:
```
[SomeModule.sql|SELECT * from table|]
```
=> Enable fontification for qualified quasiquoters

inf-haskell.el
This allows us to correctly interpret multi-line input even when modules are imported.
For reference, please see:
https://lists.gnu.org/archive/html/emacs-orgmode/2020-05/msg00852.html
This new regexp is significantly shorter than the previous regexp because it cares far less about the formatting of the Haskell prompt. The previous regexp tries to divide the prompt into two parenthesis delimited groups, but there's no clear need to do so, as long as the prompt ends with the "> " suffix.  Now, we just treat any alphanumeric character or special character, including "_*|λ .()", as part of the prompt, if they occur before the suffix.
The current haskell-prompt-regexp works in many cases, but not when GHC receives multi-line input from org-mode's ob-haskell.  This can occur when evaluating …
=> `haskell-prompt-regexp` ignores characters before the '> '.

haskell-commands.el
This PR changes the behavior of `haskell-mode-jump-to-def-or-tag` to fall back on `haskell-mode-tag-find`when `haskell-mode-find-def` fails. This fixes #351.
=> Fall back to 'haskell-mode-tag-find' when 'haskell-mode-find-def' fails in 'haskell-mode-jump-to-def-or-tag'

haskell-compile.el, haskell-customize.el, haskell-decl-scan.el
Seems ghc compilation was broken recently. Invoking haskell-compile in a buffer with a single haskell source file calls ghc with the directory and not the filename.
=> Always use buffer-file-name for ghc compilation

haskell-compile.el
When compiling a package with Stack that declares multiple packages on its `stack.yaml` file, the output of each package compilation is prepended with the string `package-name\s*>\s` like this:
```
testing> /home/javier/testing/src/Lib.hs:7:1: warning: [-Wmissing-signatures]
testing>     Top-level binding with no type signature: someFunc :: IO ()
```
Without this change, the string `testing> ` would be matched in the first part of the regexp and then emacs would fail to find the file as it would be searching for:
```
testing> /home/javier/testing/src/Lib.hs
```
as filename. The string before the `>` is also padded to the longest package name in the compilation.
The change modifies slightly the regexp to match and filter out this prefix.
Padded package:
Un-padded package:
Padded package: …
=> Add package prefix to `haskell-compilation-error-regexp-alist`

haskell-compile.el
This prevents passing TRAMP file names as arguments to external compile
commands.
Fixes #1559
=> Make sure that a local file name is used in compile commands

haskell-font-lock.el, haskell-lexeme.el, haskell-mode.el
The `!` syntax class is intended for making arbitrary pieces of text into comments; thus, tools such as `fill-paragraph` and `auto-fill-mode` treat it differently than `<`, which is intended for specifying actual comment characters.
=> Use "!" class for literate comments instead of "<" (fixes #1594)

haskell-font-lock.el, tests/haskell-font-lock-tests.el
Now the `qualified` keyword in
```haskell
import X qualified as Y
```
is correctly highlighted.
=> Add font-lock support for ImportQualifiedPost

haskell-load.el
Fixes #1757 by setting buffer `default-directory` so that the filename equality tests that use `file-truename` will line up with GHCi output.
=> Fix linting for current module when reloading another module

haskell-compile.el
Enclose the selected file's path in quotes when compiling a stand-alone Haskell file to prevent paths with spaces being parsed as multiple arguments.
Fixes #1673.
=> Fix compilation command to handle whitespace in file path

haskell-font-lock.el
See e.g. [this blogpost](https://www.haskell.org/ghc/blog/20210709-capi-usage.html) for what `capi` does. A quick example seems to indicate that `capi` is not supported in `foreign export` (which I think makes sense).
=> Add `capi` calling convention

ghc-core.el, haskell-cabal.el, haskell-compile.el, haskell-completions.el, haskell-customize.el, haskell-debug.el, haskell-decl-scan.el, haskell-doc.el, haskell-font-lock.el, haskell-indent.el, haskell-indentation.el, haskell-interactive-mode.el, haskell-load.el, inf-haskell.el, w3m-haddock.el
Generally only functions and modes should be autoloaded. add-to-list can also be
used cautiously to register modes etc. Faces are usually not autoloaded. To make
faces, groups and custom variables available for customization, a package must
be loaded.
=> Remove autoloads from face and group definitions

haskell-mode.el
{- and -} are recognised as paragraph boundaries. While this makes a lot
of sense, it does not make sense to also recognise {-# and #-} as
paragraph boundaries.
Every time I want to do something at the top of the file I go to the first line, but then if I move around as usual using paragraph-wise navigation I have to go over all the language pragmas one by one, which is super annoying.
=> Make {-# and #-} not be paragraph boundaries

haskell-commands.el, tests/haskell-mode-tests.el
I need to manually add `{-# LANUGAGE _ #-}` pragmas to the top of my modules pretty often, so I wrote a function to do this. I've been using it for a few days and found it really convenient, and other people liked the idea when I mentioned it on Twitter.
Called interactively it uses `haskell-ghc-supported-extensions` for completions which means less typing and no more errors like using `RecordWildcards` instead of `RecordWildCards`.
I bound it to `C-c C-e` on my own setup, but not sure whether it makes sense to include a keybinding for it by default.
=> Add interactive command to insert a LANGUAGE pragma

haskell-cabal.el, haskell-compile.el, haskell-customize.el, haskell-indent.el, haskell-interactive-mode.el, haskell-lexeme.el, haskell-mode.el, haskell-move-nested.el, haskell-process.el, haskell.el, inf-haskell.el, w3m-haddock.el
rel: #1779 
Hello,
When building with Emacs 28.1, there were several places where an error occurred because the docstring had more than 80 characters.
I have adjusted the number of characters per line in the docstring where the error occurs.
If there are line breaks in the wrong place, please feel free to correct it.
Thank you.
=> Fixed build errors.

haskell-commands.el
The emacs upstream will raise an error now when `otherwise` or `t` clause is not the last clause in a `cl-case`. There is a such `cl-case` in `haskell-commands.el` which is apparently a typo and should be fixed.
Reference: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=6d8f5161ead689b7a2e44a7de0a695f0ab4c833b
=> Correct parenthese matching error

haskell-collapse.el
point-at-bol and point-at-eol will be obsoleted since Emacs 29.1. This PR fixes the following byte-compile warnings.
```
In haskell-blank-line-p:
haskell-collapse.el:46:9: Warning: ‘point-at-eol’ is an obsolete function (as
of 29.1); use ‘line-end-position’ or ‘pos-eol’ instead.
In haskell-hide-toggle-all:
haskell-collapse.el:95:19: Warning: ‘point-at-bol’ is an obsolete function (as
of 29.1); use ‘line-beginning-position’ or ‘pos-bol’ instead.
```
=> Replace obsoleted functions

haskell-cabal.el, haskell-commands.el, haskell-completions.el, haskell-load.el, haskell-process.el, inf-haskell.el
Development Emacs(29.0.50) generates following byte-compile warnings. This PR fixes warnings like below ones.
```
haskell-cabal.el:704:12: Warning: Case 'before will match ‘quote’.  If that’s
intended, write (before quote) instead.  Otherwise, don’t quote ‘before’.
haskell-cabal.el:704:12: Warning: Case 'after will match ‘quote’.  If that’s
intended, write (after quote) instead.  Otherwise, don’t quote ‘after’.
haskell-cabal.el:704:12: Warning: Case 'single will match ‘quote’.  If that’s
intended, write (single quote) instead.  Otherwise, don’t quote ‘single’.
```
=> Remove needless quotes from keylist of case macro

Makefile, haskell-cabal.el, haskell-completions.el, haskell-customize.el, haskell-indent.el, haskell-indentation.el, haskell-interactive-mode.el, haskell-lexeme.el, haskell-load.el, haskell-mode.el, haskell-utils.el, haskell.el
Development Emacs(version 29) warns not escaped quotes in docstring as below. This PR fixes this issue and makes `make` command success on development Emacs too.
```
In haskell-cabal-classify-line:
haskell-cabal.el:363:2: Warning: docstring has wrong usage of unescaped single
quotes (use \= or different quoting)
```
=> Escape single quote in docstring

haskell-mode.el
If `define-derived-mode haskell-mode` comes before `defcustom haskell-mode-hook`, custom will report `haskell-mode-hook` as being changed outside of customize.  This prevents customizations from taking effect.  Swapping the order of definitions fixes this.
Fixes #1480.  Note that what @phil-s mentioned in that issue about clobbering the docstring is not a problem since Emacs 26.1, thanks to [this commit](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=3e7ebbe1bd5d33476190c789d17e4dd2d5f1bdfb), so I didn't bother with the workaround he suggested.
=> Define haskell-mode-hook before haskell-mode

haskell-hoogle.el
It's been a long time since hoogle command line interface lost the ability to
output ANSI colors (see https://github.com/ndmitchell/hoogle/issues/133).
This patch makes haskell-hoogle to use emacs font lock to fontify its output,
with a custom flag to opt out.
=> Hoogle: colorize hoogle cli output using haskell-mode font-lock

haskell-debug.el
I have tried ghc 8 and 9 on NixOS and both put extra line at the end of output about current break location, eg:
```
λ> :show breaks
[0] Main /home/me/path/Main.hs:(30,8)-(31,65) enabled
[/home/me/path/Main.hs:85:49-56] λ> 
```
Now debugger parse sections without errors. This bugfix is backward compatible.
This extra string is also shown with `haskell-doc-show-type` and break completion (when ghc is on break). Should we trim it in `haskell-process-queue-sync-request`?
#1470 could be related to this
=> fixed debugger for GHC 8/9

Makefile, doc/haskell-mode.texi, haskell-mode-pkg.el, tests/haskell-lexeme-tests.el
These are some minor fixes, like stray version numbers and some spelling errors and such. Plus one more serious change, to make it easier to debug lexical test cases by actually returning a list of tokens. This also avoids some ugly code duplication.
=> minor fixes made while trying to get debian package working with emacs 29.1

haskell-cabal.el
- Remove outdated stanzas
- Add missing keywords (elif)
- ensure `pkg:component` is not displayed as a field
=> Improve cabal font-lock

ghci-script-mode.el
The current version of `ghci-script-mode-load` is defined as 
``` elisp
(defun ghci-script-mode-load ()
"Load the current script file into the GHCi session."
(interactive)
(let ((buffer (haskell-session-interactive-buffer (haskell-session)))
(filename (buffer-file-name)))
(save-buffer)
(with-current-buffer buffer
(set-marker haskell-interactive-mode-prompt-start (point-max))
(haskell-interactive-mode-run-expr
(concat ":script " filename)))))
```
The `let` binding calls `(haskell-session-interactive-buffer (haskell-session))` which changes the current buffer by calling `(haskell-interactive-switch)` at `haskell-interactive-mode.el::520`, this causes the wrong binding for `filename` and also causes the `save-buffer` part to prompt for which file to save the `*haskell-session*` buffer in, …
=> ghci-script-mode: Fix script loading by `ghci-script-mode-load`.

haskell-mode.el
=> Require flymake-proc to avoid compilation errors in Emacs HEAD

haskell-indentation.el
This PR implements a new function `haskell-indentation-literate-outside-code-p` which may be used to detect when the point is outside a code block in both Bird-style and TeX-style literate buffers. Note that GHC accepts a mixture of both Bird-style and TeX-style delimiting in the same file, so changing the possible values of the `haskell-literate` variable might be in-scope here as well.
=> Implement indentation support for TeX-style literate Haskell buffers

haskell-load.el
Remove bad regex that was supposed to recognize a LANGUAGE suggestion.
This regex fires unfortunately on GHC 9.8's new `x-partial` warning,
destroying the UX with obnoxious questions whether to "add LANGUAGE Data".
Closes #1834.
=> Fix #1834: remove bad regex that was supposed to recognize a LANGUAGE suggestion

haskell-load.el
ghc 9.10 and later can respond to `:load` with "Failed, unloaded all modules." Unfortunately `haskell-process-load-complete` does not recognize this response. This PR fixes this. To simplify and future-proof the code I've adjusted `haskell-process-load-complete` to look for the regexes `Ok, .*$` or `Failed, .*$`. Alternatively, if you'd prefer to narrowly add the "Failed, unloaded all modules." message, [you could cherry-pick this commit.](https://github.com/haskell/haskell-mode/commit/337c41e146e47c5f92b28009c535fe9e72cfad76)
This may possibly fix https://github.com/haskell/haskell-mode/issues/1642.
=> haskell-process-load-complete: handle ghc 9.10 message

haskell-decl-scan.el
The function has implemented a poor man's hash table by manually enlisting keys and then using `cl-case` on values. Just replace this with a hashtable and thus simplify the code considerably. This makes it faster as well because the `cl-case + setq` is O(n) whereas `puthash` is O(1).
The output of the function was tested on Pandoc's
`Writers/Powerpoint/Output.hs` file of 2841 lines and comparing the hashsum of the output before the changes and after. It didn't change.
The commit is also basically a backport of a similar change on purescript-mode that has been forked form haskell-mode at some point: https://github.com/purescript-emacs/purescript-mode/pull/27
=> Optimize and simplify `haskell-ds-create-imenu-index` with hashtable

haskell-mode.el
The regex syntax `\s_` is documented at <https://www.gnu.org/software/emacs/manual/html_node/emacs/Regexp-Backslash.html>, and the syntax table entries for prime and underbar (underscore) are already set in `haskell-mode-syntax-table`.
=> Make dabbrev-expand detect underbar and prime as part of identifiers

inf-haskell.el
Hi!
I found that ob-haskell.el shows multiple prompts at any code block output. This was a little annoying for me, so I tried to fix it. Then, I realized it was from the inferior-haskell: It did not remove the prompts from the process output. 
For example, when starting an inferior Haskell with `M-x run-haskell`  and writing a multiple line function, the "\*haskell\*" buffer looks like this:
```
Loaded package environment from /home/poo/.ghc/x86_64-linux-9.0.2/environments/default
GHCi, version 9.0.2: https://www.haskell.org/ghc/  :? for help
ghci> ghci> :{
f x
| x == 0 = 1
| x < 0  = 1
| otherwise = 2 * f (x - 1)
:}
ghci| ghci| ghci| ghci| ghci| ghci> ghci> 
```
Therefore, I wrote a function to remove all prompts except for the last one. All continuation prompts (ending with "| ") are …
=> Inferior-haskell: do not insert repeated prompts.

haskell.el
_following from PR #1861_ 
Thanks a lot! This works well for me.
In the future it could be [modified to use completing-read](https://github.com/zaz/haskell-mode/compare/load-and-run-expr..completing-read?expand=1) or similar, but I find that pops up a buffer that is annoyingly large and what you wrote already works great.
=> Load and run expr

haskell-decl-scan.el
This commit adds a new user option `haskell-decl-scan-sort-imenu` to decide whether to sort the candidates in `imenu` (done in function `haskell-ds-create-imenu-index`).
When `t` (the default), sort the candidates alphabetically as before. When `nil`, present them in the same order as they appear in the file (note that this requires reversing the list of candidates, since it is built in such a way that the canditates appearing later in the file are appended to the front of the list).
=> Add user option to preserve the order of imenu candidates

haskell-c2hs.el, haskell-commands.el
This fixes a few warnings. Couldn't fix more because it complains `if-let` being an obsolete macro and that `if-let*` should be preferred, but I'm not sure what's the best course of action here. `if-let*` appeared since 26.1, so it's either upping the minimal version 26.1 or adding a wrapper for older Emacses. Emacs 26.1 was released in 2018.
=> Fix incorrect face usage and undeclared list elements type

haskell-cabal.el
Prior to this commit using (comment-dwim) over a comment in .cabal file that doesn't start at the beginning of a line resulted in it adding even more comments. E.g. this:
-- comment not at the beginning of a line
resulted in:
-- -- comment not at the beginning of a line
This is because `comment-start-skip` was including whitespace that isn't part of the comment syntax. Fix this by only limiting the regexp to the comment part.
The resulting regexp is basically same as the one in haskell-mode, barring that that one also takes into account `{-` comment starter, which isn't a thing in .cabal files.
Fixes: https://github.com/haskell/haskell-mode/issues/1743
=> haskell-cabal: fix (comment-dwim) by correcting comment-start-skip

haskell-cabal.el
The point of this space is to add padding, however in Emacs comment padding is controlled by `comment-padding` which defaults to one space exactly.
=> haskell-cabal: don't include space in `comment-start`

haskell-cabal.el
Previously it highlighted the entire line as a comment. This fixes it to ignore the leading whitespace, highlight the `--` as a comment delimiter, then highlight the remainder as the actual comment.
=> Correct Cabal comment syntax highlighting
