haskell-mode.el
=> Add customizeable blank module template

haskell-indent.el, haskell-mode.el
#475
Over a year since a release? :open_mouth:
=> Put version header only in haskell-mode.el

haskell-font-lock.el
=> Operators should be fontified. Fix #503.

haskell-process.el
https://github.com/haskell/haskell-mode/issues/460
=> let error say how to get complete support (#460)

haskell-commands.el
Using solution by ibgraimgm, proposed in issue #609
added path escaping
=> Fix hasktags call for windows

Makefile
=> Make Makefile warn if Emacs is too old.

haskell-mode.el
Make #522 and #375 a bit better.
=> Improve interacton setup message.

haskell-commands.el, haskell-interactive-mode.el, haskell-presentation-mode.el
=> Make Haskell Presentation buffer the only

haskell-font-lock.el
=> Prevent keyword symbols redefinition

haskell-commands.el
Pinging @gracjan. Please merge as soon as possible (:
Related to #689
=> Add missing parentheses

COPYING
Related wiki updated https://github.com/haskell/haskell-mode/wiki/Contributing/_compare/66188df9358b6c81fe5e7b62a0b967c81fd87270...4f3418455fa841fcda7b1f7eba9dd8eb9d48d5bb
=> Add GNU GPL COPYING file

tests/haskell-indentation-tests.el
Documents a working case such as #712.
=> Add test layout versus comma in braces

ghci-script-mode.el
docstring should appear before function body.
=> Fix docstring position

Makefile
I opened an issue about this earlier and it turned out to be really easy to fix: https://github.com/haskell/haskell-mode/issues/791.
=> Fix not being able to compile from within emacs

doc/haskell-mode.texi, haskell-customize.el
Step 2 of https://github.com/haskell/haskell-mode/issues/667
=> Remove haskell-customize function

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Normalize Unicode symbols to ASCII versions

tests/haskell-indentation-tests.el
=> Add test case documenting indentation and type problem

tests/haskell-indentation-tests.el
Test for https://github.com/haskell/haskell-mode/issues/883
=> Parse unindented where-clause properly

tests/haskell-indentation-tests.el
Bunch of failing test cases for indentation I collected while using haskell-mode. I hope they'll be useful
=> Add failing tests for indentation

tests/haskell-indentation-tests.el
=> Document failing indentation

haskell-commands.el
Fixes https://github.com/haskell/haskell-mode/issues/923.
=> Don't change directory when using stack-ghci.

tests/haskell-indentation-tests.el
=> Yet another parser failure

haskell-font-lock.el
This acronym can be confused with the Linux firmware w.r.t. With regards to is perfectly clear.
=> Change 'w.r.t' to 'with regards to' for clarity

tests/haskell-indentation-tests.el
This is suggested as a test case in #1000.
=> Add test for a case expression with multiple paths on their own lines.

haskell-mode.el, tests/haskell-mode-tests.el
=> Properly separate haddock paragraphs

haskell-font-lock.el
=> Add type role to font lock

haskell-load.el
Also stick to 80 columns width whenever it possible.
Add proper el-package wrap, note this reveals a lot warnings.
TODO: fix docstring warnings.
=> Tidy up haskell-load.el: untabify, reindent.  Fix some warnings.

haskell-compile.el, haskell-load.el
Also remove extra error parsing.
Fixes #1107
=> Support spaces in project directories

haskell-mode.el
=> Fix snapshot build

haskell-mode.el
=> Properly find begin of a quasiquote

haskell-interactive-mode.el, tests/interactive-haskell-mode-tests.el
Reverts haskell/haskell-mode#1121
=> Revert "Remove suggested imports completely"

tests/haskell-indentation-tests.el
Adds the test above another similar (failing) test. For #1154
=> Deriving indentatation test

Makefile
=> Makefile dependency tracking improvements

haskell-c2hs.el, haskell-utils.el, tests/haskell-c2hs-tests.el
=> C2hs fixes

doc/haskell-mode.texi
=> Move content from wiki to manual

haskell-font-lock.el
=> Change default for haskell-type-face

haskell-font-lock.el, tests/haskell-font-lock-tests.el
=> Fix double negation issue in dot fontification

haskell-lexeme.el, tests/haskell-font-lock-tests.el
=> Add escape sequences to char literals

haskell-completions.el
=> Fix 1234: tags-completion-table

haskell-completions.el, haskell-mode.el
=> Autoload haskell-completions-completion-at-point

doc/haskell-mode.texi, haskell-commands.el
=> Use :set +c in GHCi

doc/haskell-mode.texi, haskell-completions.el, tests/haskell-completions-tests.el
=> Fix completion after operator

Makefile, haskell-interactive-mode.el, haskell-mode.el, w3m-haddock.el
=> Compile sources separately

haskell-mode.el, haskell.el, tests/haskell-mode-tests.el
=> Improve guess module name

haskell-commands.el, tests/haskell-mode-tests.el
=> Make stylish-haskell keep the point position

haskell.el
Fixes #856.
Note that I did not introduce any new bindings as it is unclear what could those be.
=> Remove controversial keybindings

haskell-compile.el, haskell-interactive-mode.el, haskell-mode.el, haskell-unicode-input-method.el
=> Remove references to info nodes

haskell-font-lock.el
=> Add haskell-yesod-parse-routes-mode-keywords

haskell-process.el
Fix bugs visible in coding style. Fixes #1283.
=> Fix a couple obvious issues in haskell-process-log

haskell-indentation.el
=> Fix indentation when breaking identifiers by newline

haskell-modules.el
=> Ignore warnings from ghc-pkg

haskell-font-lock.el, haskell-mode.el, tests/haskell-font-lock-tests.el
=> Support line continuation in CPP

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Support unterminated strings in indentation

haskell-interactive-mode.el
=> Make session buffer name unique

haskell-indentation.el, tests/haskell-indentation-tests.el
=> Operators at the end or beggining of line force continuation

haskell-interactive-mode.el
=> Use haskell-mode syntax table in interactive mode

.travis.yml, Makefile, tests/haskell-external.el
=> Check some packages depending on haskell-mode

haskell-cabal.el, tests/haskell-cabal-tests.el
=> Fix auto add dependencies in cabal

Makefile
Fix https://github.com/haskell/haskell-mode/issues/1409
=> Makefile: Remove extra quote that breaks the build

haskell-indentation.el
=> Fix module indentation

haskell-customize.el
=> add "--no-build" and "--no-load" to haskell-process-args-stack-ghci

haskell-font-lock.el, tests/haskell-font-lock-tests.el
=> Implement forall as keyword in type context

haskell-lexeme.el
=> Take into account end of buffer

README.md
=> Fix up installation instructions

haskell-interactive-mode.el
=> Fix a typo

haskell-interactive-mode.el, haskell-load.el
=> GHC8 warning case change

haskell-commands.el, haskell-string.el, haskell.el
=> Fix jumping to qualified names

tests/haskell-test-utils-tests.el, tests/haskell-test-utils.el
+ fix for with-temp-dir macro
+ kill buffer unconditionally
+ addition of other util functions to bypass confirmation
=> haskell-test-utils

appveyor.yml
+ `--no-progress` with `choco`
+ fixes #1541
=> Appveyor less verbose

haskell-lexeme.el
=> Fix syntax highlighting for TypeOperators in type

haskell-hoogle.el
This version of Hoogle is newer and has a larger index.
=> Switch to a better Hoogle

haskell-font-lock.el
Fixes https://github.com/haskell/haskell-mode/issues/1631.
=> Don't specify line endings

haskell-commands.el, haskell-customize.el, haskell-hoogle.el, haskell-load.el
Fixes #1718.
Also, Hayoo should be removed, since it seems dead.
=> Make Hoogle work in Nix shell

haskell-hoogle.el
=> Restore `haskell-hoogle-command` configurability

haskell-decl-scan.el
As discussed in #1726 
Thanks!
=> Remove scanning/sorting declarations messages from imenu index creation

.github/workflows/test.yml, haskell-doc.el, haskell-mode.el, tests/haskell-doc-tests.el
=> Haskell doc mode tidyup

haskell-cabal.el
Sublibraries and program-options were not contemplated
=> Add new cabal stanzas to font-lock

haskell-debug.el
This fix the behaviour of /abandon and /continue function.
=> debugger: macro bugfix

haskell-indentation.el
=> Apply suggested improvement to tex indentation predicate

haskell-cabal.el
Fixes [#1826](https://github.com/haskell/haskell-mode/issues/1826).
=> haskell-cabal: fix indentation with leading commas and newlines
